=== CIRCL/open-data-security/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for open-data-security format",
  "id": "https://github.com/CIRCL/open-data-security/blob/master/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "number"
    },
    "source": {
      "type": "array",
      "uniqueItems": true
    },
    "tags": {
      "type": "array",
      "uniqueItems": true,
      "$comment": "tag SHOULD come from a MISP taxonomy namespace"
    },
    "title": {
      "type": "string",
      "$comment": "a comprehensive and concise title of the dataset"
    },
    "subtitle": {
      "type": "string",
      "$comment": "an extended title of the dataset"
    },
    "description": {
      "type": "string",
      "$comment": "an exhaustive description of the dataset including methods of collection, extraction or analysis"
    },
    "time-precision": {
      "type": "string",
      "$comment": "time-precision MUST be expressed in years, months, days, hours, minutes or seconds to describe the precision of the time expressed"
    },
    "frequency": {
      "type": "string",
      "$comment": "frequency of the dataset generation which MUST be expressed in yearly, monthly, daily, hourly, continuous"
    },
    "producer": {
      "type": "string",
      "$comment": "producer MUST be expressed as an URI to reference the original producer of the dataset"
    },
    "license": {
      "type": "string",
      "$comment": "license MUST be expressed in SPDX format to describe under which license the dataset is distributed"
    },
    "human-validated": {
      "type": "boolean",
      "$comment": "human-validated describes if the dataset has been manually validated"
    },
    "machine-validated": {
      "type": "boolean",
      "$comment": "machine-validated describes if the dataset has been automatically validated"
    }
  },
  "required": [
    "title",
    "license"
  ]
}

=== CIRCL/open-data-security/sample/sample.json
{
  "human-validated": false,
  "machine-validated": true,
  "title": "DNS queries",
  "subtitle": "Extracted DNS queries from a set of distributed honeypots",
  "description": "DNS queries extracted from the network captures of a distributed set of honeypots.",
  "frequency": "daily",
  "time-precision": "seconds",
  "source": [
    "honeybot-1234",
    "honeybot-1235"
  ],
  "license": "CC-BY-4.0",
  "producer": "https://www.circl.lu/",
  "tags": [
    "honeypot-basic:interaction-level=\"none\"",
    "honeypot-basic:data-capture=\"network-capture\"",
    "tlp:clear"
  ]
}
